CREATE ROLE art_user SUPERUSER PASSWORD 'postgres';
CREATE SCHEMA art AUTHORIZATION postgres;

CREATE TABLE IF NOT EXISTS USER (
 id UUID NOT NULL,
 first_name TEXT NOT NULL,
 last_name TEXT NOT NULL,
 email_id TEXT NOT NULL,
 created_date TEXT NOT NULL,
 PRIMARY KEY (id)
);